# .github/workflows/develop-cd.yaml
name: CD - Deploy to Development Environment

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages (Development)
    runs-on: ubuntu-latest
    environment:
      name: development-env
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./src/index.html

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
